version: "3"

services:
  sshd-server:
    build: .
    container_name: ${USERNAME}-server
    hostname: ${USERNAME}-server
    volumes:
      - home:/root
      - type: bind
        source: ./users/${USERNAME}/cred
        target: /cred
    networks:
      - proxy

volumes:
  home:

networks:
  proxy:
    external: true
