version: "3"

services:
  sshd-server:
    build: .
    container_name: ${USERNAME}-server
    hostname: ${USERNAME}-server
    ports:
      - "${SSH_PORT}:22"
    volumes:
      - home:/root
      - ./users/${USERNAME}/cred:/cred
    networks:
      - proxy
      - db
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: ${USERNAME}-db
    environment:
      - MYSQL_ROOT_PASSWORD=tnfqkrtm
    volumes:
      - data:/var/lib/mysql
    networks:
      - db

volumes:
  home:
  data:

networks:
  proxy:
    external: true
  db:
