version: "3"

services:
  sshd-server:
    build: .
    container_name: ${USERNAME}-server
    hostname: ${USERNAME}-server
    ports:
      - "${SSH_PORT}:22"
    volumes:
      - home:/root
      - ./users/${USERNAME}/cred:/cred
    networks:
      - proxy

volumes:
  home:

networks:
  proxy:
    external: true
